name: Merge queue
on:
  merge_group:

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Show files in merge run
        run: |
          pwd
          tree -a -I '.git'
          git status
          ls -al
          sleep 120
      - name: Fail this job
        run: |
          exit 1
