name: Merge queue
on:
  merge_group:

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Reset staging branch
        uses: Joao208/resync-branch@1.5.0
        with:
          PERSONAL_TOKEN: ${{secrets.GITHUB_TOKEN}}
          BRANCH_NAME: staging
          DEFAULT_BRANCH: main
      - name: Merge PR branch to staging
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: ${{ github.ref }}
          target_branch: staging
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Show files in merge run
        run: |
          pwd
          tree -a -I '.git'
          git status
          ls -al
          sleep 60
          exit 1
