# This is a basic workflow to help you get started with Actions

name: Merge queue

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  merge_group:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    concurrency:
      group: merge-queue
      cancel-in-progress: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Show files in merge run
        run: |
          ls -al

      # Runs a set of commands using the runners shell
      - name: Fail this job
        run: |
          exit 1
